### ISSUE TITLE
Mutaqarib not being recognized

### ISSUE THREAD

**Issue by aboudaty** [kariminf/aruudy#16]
Salam Brother,

I love your work! Thank you for putting in all this effort to help Arabic content. I tried the following shatr in the web API:

هِلَالَ الرَّبِيْعِ عَلَيْكَ السَّلَام

https://kariminf.pythonanywhere.com/shatr/%D9%87%D9%90%D9%84%D9%8E%D8%A7%D9%84%D9%8E%20%D8%A7%D9%84%D8%B1%D9%91%D9%8E%D8%A8%D9%90%D9%8A%D9%92%D8%B9%D9%90%20%D8%B9%D9%8E%D9%84%D9%8E%D9%8A%D9%92%D9%83%D9%8E%20%D8%A7%D9%84%D8%B3%D9%91%D9%8E%D9%84%D9%8E%D8%A7%D9%85

And it gave me the result of it being Muqtadab rather than Mutaqarib. If I can help in any way, please let me know. 

Best,
Abdul-Rahman

**Comment by kariminf** [comment]
Salam brother, 
Thank you for the encouragement. 
I added "QASR" into the last "Tafiila" of "Mutaqarib" 
Now, it works
Thank you for reporting
