### ISSUE TITLE
No module named aruudy.lists

### ISSUE THREAD

**Issue by hash0anas** [kariminf/aruudy#17]
When I run this command in python `from aruudy.poetry import prosody`

I get the error ModuleNotFoundError: No module named 'aruudy.lists'

Python version 3.6
Windows 10 64-bit

**Comment by kariminf** [comment]
It is fixed in release 0.5.1. The problem in version 0.5: I forgot to include arrudy.lists 

To update : 

pip install aruudy -U

Thanks for your feedback
