### ISSUE TITLE
Bahr.get_names()

### ISSUE THREAD

**Issue by linuxscout** [kariminf/aruudy#21]
This methodes gives errors on python3
It says that Bahr has not a get_value method

**Comment by kariminf** [comment]
It is a sort of abstract class (abstract classes do not exist in python per se). The information needed by this method but be completed during instantiation. 
For example, et the line 427; all Bahres are defined:
 `tawiil = Bahr({
    "name": {
        "arabic": u"طويل",
        "english": "long",
        "trans": u"ṭawīl"
    },
    "meter": [
        BahrForm([
        foot.WWSWS([FT.SALIM, FT.QABDH]),
        foot.WWSWSWS([FT.SALIM, FT.QABDH, FT.KAFF]),
        foot.WWSWS([FT.SALIM, FT.QABDH]),
        foot.WWSWSWS([FT.QABDH]),
        ])
    ],
    "key": u"طويلٌ له دون البحور فضائلٌ  فعولن مفاعيلن فعولن مفاعلن"
})`

When you call tawiil.get_names(), it will work.

**Comment by linuxscout** [comment]
I used it like this
```python
def get_bahr(text):
    """
    get arabic name of bahr
    """
    shatr = prosody.process_shatr(text)
    #get the bahr: it has aname, ename, trans,
    b = shatr.bahr
    if b:
        b_arabic = "ال"+b.name.get("arabic", "")
        return b_arabic
    else:
        return ""
```

**Comment by kariminf** [comment]
fixed
